[build]
  base = "client"  # The directory where your React app is located
  publish = "client/build"  # The build directory of your React app
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
